In [1]:

import ibmos2spark

# @hidden_cell
credentials = {
    'endpoint': 'https://s3-api.us-geo.objectstorage.service.networklayer.com',
    'api_key': 'xudPJJlt6zip-7O9rVbpPlACpn431fGyU5WpM8bCc4Sa',
    'service_id': 'iam-ServiceId-7221825f-4dee-4435-b2d3-9cde0c6240d7',
    'iam_service_endpoint': 'https://iam.bluemix.net/oidc/token'}

configuration_name = 'os_df422aab2710455eaea2225ddc7adc37_configs'
cos = ibmos2spark.CloudObjectStorage(sc, credentials, configuration_name, 'bluemix_cos')

from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()
df_data_1 = spark.read\
  .format('org.apache.spark.sql.execution.datasources.csv.CSVFileFormat')\
  .option('header', 'true')\
  .option('inferschema','true')\
  .load(cos.url('bigml_59c28831336c6604c800002a.csv', 'default-donotdelete-pr-e49dfxtaag7tpq'))
df_data_1.show()

+-----+--------------+---------+------------+------------------+---------------+---------------------+-----------------+---------------+----------------+-----------------+---------------+----------------+-------------------+-----------------+------------------+------------------+----------------+-----------------+----------------------+-----+
|state|account length|area code|phone number|international plan|voice mail plan|number vmail messages|total day minutes|total day calls|total day charge|total eve minutes|total eve calls|total eve charge|total night minutes|total night calls|total night charge|total intl minutes|total intl calls|total intl charge|customer service calls|churn|
+-----+--------------+---------+------------+------------------+---------------+---------------------+-----------------+---------------+----------------+-----------------+---------------+----------------+-------------------+-----------------+------------------+------------------+----------------+-----------------+----------------------+-----+
|   KS|           128|      415|    382-4657|                no|            yes|                   25|            265.1|            110|           45.07|            197.4|             99|           16.78|              244.7|               91|             11.01|              10.0|               3|              2.7|                     1|false|
|   OH|           107|      415|    371-7191|                no|            yes|                   26|            161.6|            123|           27.47|            195.5|            103|           16.62|              254.4|              103|             11.45|              13.7|               3|              3.7|                     1|false|
|   NJ|           137|      415|    358-1921|                no|             no|                    0|            243.4|            114|           41.38|            121.2|            110|            10.3|              162.6|              104|              7.32|              12.2|               5|             3.29|                     0|false|
|   OH|            84|      408|    375-9999|               yes|             no|                    0|            299.4|             71|            50.9|             61.9|             88|            5.26|              196.9|               89|              8.86|               6.6|               7|             1.78|                     2|false|
|   OK|            75|      415|    330-6626|               yes|             no|                    0|            166.7|            113|           28.34|            148.3|            122|           12.61|              186.9|              121|              8.41|              10.1|               3|             2.73|                     3|false|
|   AL|           118|      510|    391-8027|               yes|             no|                    0|            223.4|             98|           37.98|            220.6|            101|           18.75|              203.9|              118|              9.18|               6.3|               6|              1.7|                     0|false|
|   MA|           121|      510|    355-9993|                no|            yes|                   24|            218.2|             88|           37.09|            348.5|            108|           29.62|              212.6|              118|              9.57|               7.5|               7|             2.03|                     3|false|
|   MO|           147|      415|    329-9001|               yes|             no|                    0|            157.0|             79|           26.69|            103.1|             94|            8.76|              211.8|               96|              9.53|               7.1|               6|             1.92|                     0|false|
|   LA|           117|      408|    335-4719|                no|             no|                    0|            184.5|             97|           31.37|            351.6|             80|           29.89|              215.8|               90|              9.71|               8.7|               4|             2.35|                     1|false|
|   WV|           141|      415|    330-8173|               yes|            yes|                   37|            258.6|             84|           43.96|            222.0|            111|           18.87|              326.4|               97|             14.69|              11.2|               5|             3.02|                     0|false|
|   IN|            65|      415|    329-6603|                no|             no|                    0|            129.1|            137|           21.95|            228.5|             83|           19.42|              208.8|              111|               9.4|              12.7|               6|             3.43|                     4| true|
|   RI|            74|      415|    344-9403|                no|             no|                    0|            187.7|            127|           31.91|            163.4|            148|           13.89|              196.0|               94|              8.82|               9.1|               5|             2.46|                     0|false|
|   IA|           168|      408|    363-1107|                no|             no|                    0|            128.8|             96|            21.9|            104.9|             71|            8.92|              141.1|              128|              6.35|              11.2|               2|             3.02|                     1|false|
|   MT|            95|      510|    394-8006|                no|             no|                    0|            156.6|             88|           26.62|            247.6|             75|           21.05|              192.3|              115|              8.65|              12.3|               5|             3.32|                     3|false|
|   IA|            62|      415|    366-9238|                no|             no|                    0|            120.7|             70|           20.52|            307.2|             76|           26.11|              203.0|               99|              9.14|              13.1|               6|             3.54|                     4|false|
|   NY|           161|      415|    351-7269|                no|             no|                    0|            332.9|             67|           56.59|            317.8|             97|           27.01|              160.6|              128|              7.23|               5.4|               9|             1.46|                     4| true|
|   ID|            85|      408|    350-8884|                no|            yes|                   27|            196.4|            139|           33.39|            280.9|             90|           23.88|               89.3|               75|              4.02|              13.8|               4|             3.73|                     1|false|
|   VT|            93|      510|    386-2923|                no|             no|                    0|            190.7|            114|           32.42|            218.2|            111|           18.55|              129.6|              121|              5.83|               8.1|               3|             2.19|                     3|false|
|   VA|            76|      510|    356-2992|                no|            yes|                   33|            189.7|             66|           32.25|            212.8|             65|           18.09|              165.7|              108|              7.46|              10.0|               5|              2.7|                     1|false|
|   TX|            73|      415|    373-2782|                no|             no|                    0|            224.4|             90|           38.15|            159.5|             88|           13.56|              192.8|               74|              8.68|              13.0|               2|             3.51|                     1|false|
+-----+--------------+---------+------------+------------------+---------------+---------------------+-----------------+---------------+----------------+-----------------+---------------+----------------+-------------------+-----------------+------------------+------------------+----------------+-----------------+----------------------+-----+
only showing top 20 rows

In [2]:
df_data_1.printSchema()

root
 |-- state: string (nullable = true)
 |-- account length: integer (nullable = true)
 |-- area code: integer (nullable = true)
 |-- phone number: string (nullable = true)
 |-- international plan: string (nullable = true)
 |-- voice mail plan: string (nullable = true)
 |-- number vmail messages: integer (nullable = true)
 |-- total day minutes: double (nullable = true)
 |-- total day calls: integer (nullable = true)
 |-- total day charge: double (nullable = true)
 |-- total eve minutes: double (nullable = true)
 |-- total eve calls: integer (nullable = true)
 |-- total eve charge: double (nullable = true)
 |-- total night minutes: double (nullable = true)
 |-- total night calls: integer (nullable = true)
 |-- total night charge: double (nullable = true)
 |-- total intl minutes: double (nullable = true)
 |-- total intl calls: integer (nullable = true)
 |-- total intl charge: double (nullable = true)
 |-- customer service calls: integer (nullable = true)
 |-- churn: boolean (nullable = true)

In [3]:
df_data_1.columns

['state',
 'account length',
 'area code',
 'phone number',
 'international plan',
 'voice mail plan',
 'number vmail messages',
 'total day minutes',
 'total day calls',
 'total day charge',
 'total eve minutes',
 'total eve calls',
 'total eve charge',
 'total night minutes',
 'total night calls',
 'total night charge',
 'total intl minutes',
 'total intl calls',
 'total intl charge',
 'customer service calls',
 'churn']

In [4]:
data=df_data_1.drop('state','voice mail plan')
data.printSchema()

root
 |-- account length: integer (nullable = true)
 |-- area code: integer (nullable = true)
 |-- phone number: string (nullable = true)
 |-- international plan: string (nullable = true)
 |-- number vmail messages: integer (nullable = true)
 |-- total day minutes: double (nullable = true)
 |-- total day calls: integer (nullable = true)
 |-- total day charge: double (nullable = true)
 |-- total eve minutes: double (nullable = true)
 |-- total eve calls: integer (nullable = true)
 |-- total eve charge: double (nullable = true)
 |-- total night minutes: double (nullable = true)
 |-- total night calls: integer (nullable = true)
 |-- total night charge: double (nullable = true)
 |-- total intl minutes: double (nullable = true)
 |-- total intl calls: integer (nullable = true)
 |-- total intl charge: double (nullable = true)
 |-- customer service calls: integer (nullable = true)
 |-- churn: boolean (nullable = true)

In [5]:
data.groupby('churn').count().show()

+-----+-----+
|churn|count|
+-----+-----+
| true|  483|
|false| 2850|
+-----+-----+

In [6]:
data.groupby('international plan').count().show()

+------------------+-----+
|international plan|count|
+------------------+-----+
|                no| 3010|
|               yes|  323|
+------------------+-----+

In [7]:
print("There are {} records ".format(data.count()))

There are 3333 records

In [8]:
data.groupby('total night calls').count().show()

+-----------------+-----+
|total night calls|count|
+-----------------+-----+
|              148|    4|
|              137|   11|
|               85|   44|
|               65|   14|
|               53|    6|
|              133|   14|
|               78|   40|
|              108|   64|
|              155|    2|
|              115|   51|
|              126|   27|
|              101|   52|
|               81|   33|
|               76|   41|
|               44|    1|
|              103|   65|
|               91|   76|
|              128|   25|
|              122|   31|
|               93|   58|
+-----------------+-----+
only showing top 20 rows

In [9]:
data.groupby('total eve calls').count().show()

+---------------+-----+
|total eve calls|count|
+---------------+-----+
|            148|    2|
|             85|   47|
|            137|   14|
|             65|   19|
|             53|    3|
|            133|   17|
|             78|   40|
|            108|   71|
|            155|    3|
|            101|   68|
|            115|   60|
|            126|   30|
|             81|   34|
|             76|   30|
|             44|    1|
|            159|    1|
|            103|   64|
|             12|    1|
|             91|   56|
|            128|   28|
+---------------+-----+
only showing top 20 rows

In [10]:
print("There are {} columns in this dataset".format(len(data.columns)))
print(("The columns are :"),data.columns)

There are 19 columns in this dataset
The columns are : ['account length', 'area code', 'phone number', 'international plan', 'number vmail messages', 'total day minutes', 'total day calls', 'total day charge', 'total eve minutes', 'total eve calls', 'total eve charge', 'total night minutes', 'total night calls', 'total night charge', 'total intl minutes', 'total intl calls', 'total intl charge', 'customer service calls', 'churn']

In [11]:
data.describe('customer service calls').show()

+-------+----------------------+
|summary|customer service calls|
+-------+----------------------+
|  count|                  3333|
|   mean|    1.5628562856285628|
| stddev|    1.3154910448664752|
|    min|                     0|
|    max|                     9|
+-------+----------------------+

In [12]:
data.describe('total intl calls').show()

+-------+------------------+
|summary|  total intl calls|
+-------+------------------+
|  count|              3333|
|   mean|4.4794479447944795|
| stddev|2.4612142705460953|
|    min|                 0|
|    max|                20|
+-------+------------------+

In [13]:
data.select('area code','total night calls').show()

+---------+-----------------+
|area code|total night calls|
+---------+-----------------+
|      415|               91|
|      415|              103|
|      415|              104|
|      408|               89|
|      415|              121|
|      510|              118|
|      510|              118|
|      415|               96|
|      408|               90|
|      415|               97|
|      415|              111|
|      415|               94|
|      408|              128|
|      510|              115|
|      415|               99|
|      415|              128|
|      408|               75|
|      510|              121|
|      510|              108|
|      415|               74|
+---------+-----------------+
only showing top 20 rows

In [14]:
data.select('area code').distinct().count()

3

In [15]:
data.select('area code').count()

3333

In [16]:
data.crosstab('phone number','churn').show()

+------------------+-----+----+
|phone number_churn|false|true|
+------------------+-----+----+
|          328-8808|    1|   0|
|          418-4365|    1|   0|
|          345-7117|    1|   0|
|          327-9289|    1|   0|
|          334-6519|    0|   1|
|          339-6637|    0|   1|
|          383-6544|    1|   0|
|          383-6356|    1|   0|
|          332-7607|    1|   0|
|          366-4467|    1|   0|
|          376-4271|    1|   0|
|          355-1113|    1|   0|
|          344-3466|    0|   1|
|          366-4287|    1|   0|
|          360-2690|    1|   0|
|          341-7686|    0|   1|
|          420-6324|    0|   1|
|          382-1399|    1|   0|
|          416-7591|    1|   0|
|          349-2654|    1|   0|
+------------------+-----+----+
only showing top 20 rows

In [17]:
data.select('phone number','churn').dropDuplicates().show()

+------------+-----+
|phone number|churn|
+------------+-----+
|    356-2992|false|
|    400-3150|false|
|    339-7541| true|
|    375-3003|false|
|    414-9054|false|
|    365-3562|false|
|    329-2789|false|
|    352-1127|false|
|    372-1493|false|
|    415-6145|false|
|    405-7676| true|
|    417-6906|false|
|    344-4022|false|
|    333-9133|false|
|    360-5636|false|
|    376-4665|false|
|    412-6019|false|
|    420-3028|false|
|    421-1326| true|
|    348-9383|false|
+------------+-----+
only showing top 20 rows

In [18]:

df_data = df_data_1.withColumn("churn", df_data_1["churn"].cast("int"))

In [19]:
df_data.printSchema()

root
 |-- state: string (nullable = true)
 |-- account length: integer (nullable = true)
 |-- area code: integer (nullable = true)
 |-- phone number: string (nullable = true)
 |-- international plan: string (nullable = true)
 |-- voice mail plan: string (nullable = true)
 |-- number vmail messages: integer (nullable = true)
 |-- total day minutes: double (nullable = true)
 |-- total day calls: integer (nullable = true)
 |-- total day charge: double (nullable = true)
 |-- total eve minutes: double (nullable = true)
 |-- total eve calls: integer (nullable = true)
 |-- total eve charge: double (nullable = true)
 |-- total night minutes: double (nullable = true)
 |-- total night calls: integer (nullable = true)
 |-- total night charge: double (nullable = true)
 |-- total intl minutes: double (nullable = true)
 |-- total intl calls: integer (nullable = true)
 |-- total intl charge: double (nullable = true)
 |-- customer service calls: integer (nullable = true)
 |-- churn: integer (nullable = true)

In [20]:
d1=data.drop('international plan')

In [21]:
d1.printSchema()

root
 |-- account length: integer (nullable = true)
 |-- area code: integer (nullable = true)
 |-- phone number: string (nullable = true)
 |-- number vmail messages: integer (nullable = true)
 |-- total day minutes: double (nullable = true)
 |-- total day calls: integer (nullable = true)
 |-- total day charge: double (nullable = true)
 |-- total eve minutes: double (nullable = true)
 |-- total eve calls: integer (nullable = true)
 |-- total eve charge: double (nullable = true)
 |-- total night minutes: double (nullable = true)
 |-- total night calls: integer (nullable = true)
 |-- total night charge: double (nullable = true)
 |-- total intl minutes: double (nullable = true)
 |-- total intl calls: integer (nullable = true)
 |-- total intl charge: double (nullable = true)
 |-- customer service calls: integer (nullable = true)
 |-- churn: boolean (nullable = true)

In [22]:
from pyspark.ml.linalg import Vectors
from pyspark.ml.feature import VectorAssembler

In [23]:

assembler=VectorAssembler(inputCols=['account length','area code','number vmail messages','total day minutes',
                                     'total day calls','total day charge','total eve minutes','total eve calls','total night minutes',
                                     'total night calls','total night charge','total intl minutes',
                                     'total intl calls','total intl charge','customer service calls'],outputCol='features')
 
output_data=assembler.transform(df_data)

In [24]:
output_data.printSchema()

root
 |-- state: string (nullable = true)
 |-- account length: integer (nullable = true)
 |-- area code: integer (nullable = true)
 |-- phone number: string (nullable = true)
 |-- international plan: string (nullable = true)
 |-- voice mail plan: string (nullable = true)
 |-- number vmail messages: integer (nullable = true)
 |-- total day minutes: double (nullable = true)
 |-- total day calls: integer (nullable = true)
 |-- total day charge: double (nullable = true)
 |-- total eve minutes: double (nullable = true)
 |-- total eve calls: integer (nullable = true)
 |-- total eve charge: double (nullable = true)
 |-- total night minutes: double (nullable = true)
 |-- total night calls: integer (nullable = true)
 |-- total night charge: double (nullable = true)
 |-- total intl minutes: double (nullable = true)
 |-- total intl calls: integer (nullable = true)
 |-- total intl charge: double (nullable = true)
 |-- customer service calls: integer (nullable = true)
 |-- churn: integer (nullable = true)
 |-- features: vector (nullable = true)

In [25]:
final_data=output_data.select('features','churn')

In [26]:
from pyspark.ml.classification import LogisticRegression

In [27]:
train,test=final_data.randomSplit([0.7,0.3])

In [28]:
model=LogisticRegression(maxIter=10, regParam=0.3, elasticNetParam=0.8,labelCol='churn')

In [29]:
model=model.fit(train)

In [30]:
summary=model.summary
summary.predictions.describe().show()

+-------+-------------------+----------+
|summary|              churn|prediction|
+-------+-------------------+----------+
|  count|               2335|      2335|
|   mean|0.14903640256959313|       0.0|
| stddev| 0.3562006332582559|       0.0|
|    min|                0.0|       0.0|
|    max|                1.0|       0.0|
+-------+-------------------+----------+

In [36]:
from pyspark.ml.evaluation import MulticlassClassificationEvaluator
predictions=model.evaluate(test)
evaluator=MulticlassClassificationEvaluator(metricName="accuracy",predictionCol='prediction',labelCol='churn')
 
accuracy=evaluator.evaluate(predictions.predictions)
 
model1=LogisticRegression(maxIter=10, regParam=0.3, elasticNetParam=0.8,labelCol='churn')
model1=model1.fit(final_data)
 
test_data=assembler.transform(df_data)
print("Accuracy = %g " % ( accuracy))

Accuracy = 0.864729

In [37]:
results=model1.transform(test_data)
 
results.select('phone number','state','prediction').show()

+------------+-----+----------+
|phone number|state|prediction|
+------------+-----+----------+
|    382-4657|   KS|       0.0|
|    371-7191|   OH|       0.0|
|    358-1921|   NJ|       0.0|
|    375-9999|   OH|       0.0|
|    330-6626|   OK|       0.0|
|    391-8027|   AL|       0.0|
|    355-9993|   MA|       0.0|
|    329-9001|   MO|       0.0|
|    335-4719|   LA|       0.0|
|    330-8173|   WV|       0.0|
|    329-6603|   IN|       0.0|
|    344-9403|   RI|       0.0|
|    363-1107|   IA|       0.0|
|    394-8006|   MT|       0.0|
|    366-9238|   IA|       0.0|
|    351-7269|   NY|       0.0|
|    350-8884|   ID|       0.0|
|    386-2923|   VT|       0.0|
|    356-2992|   VA|       0.0|
|    373-2782|   TX|       0.0|
+------------+-----+----------+
only showing top 20 rows